#!/bin/bash

echo "🔥 Running start.sh"

# 🔧 Core Langflow ENV (not globals)
echo "🔧 CORS_ALLOW_ORIGINS=$CORS_ALLOW_ORIGINS"
echo "🔧 LANGFLOW_DATABASE_URL=$LANGFLOW_DATABASE_URL"
echo "🔧 LANGFLOW_LOG_LEVEL=$LANGFLOW_LOG_LEVEL"
echo "🔧 LANGFLOW_PORT=$LANGFLOW_PORT"

# 🌐 Variables to inject into Langflow Globals
echo "🌐 OPENAI_API_KEY=$OPENAI_API_KEY"
echo "🌐 SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY"
echo "🌐 SUPABASE_TABLE_NAME=$SUPABASE_TABLE_NAME"
echo "🌐 SUPABASE_URL=$SUPABASE_URL"
echo "🌐 UNSTRUCTURED_API_KEY=$UNSTRUCTURED_API_KEY"
echo "🌐 UNSTRUCTURED_API_URL=$UNSTRUCTURED_API_URL"
echo "🌐 MEM0_API_KEY=$MEM0_API_KEY"
echo "🌐 PORT=$PORT"

# ✅ Set which ENV vars should be injected into Langflow Globals
export LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT="OPENAI_API_KEY,SUPABASE_SERVICE_KEY,SUPABASE_TABLE_NAME,SUPABASE_URL,UNSTRUCTURED_API_KEY,UNSTRUCTURED_API_URL,MEM0_API_KEY,PORT"

echo "🚀 Starting Langflow with injected ENV globals..."
exec langflow run --host 0.0.0.0 --port ${PORT:-7860}